'''
A set of musical shorthands for use in programming Valerie's
sound design engine.
'''

# STEPS
WHOLE = 2
HALF = 1

# ((G#,Ab),(A#,Bb)...)

# MODES
IONIAN = [WHOLE,WHOLE,HALF,WHOLE,WHOLE,WHOLE,HALF]
DORIAN = [WHOLE,HALF,WHOLE,WHOLE,WHOLE,HALF,WHOLE]
PHRYGIAN = [HALF,WHOLE,WHOLE,WHOLE,HALF,WHOLE,WHOLE]
LYDIAN = [WHOLE,WHOLE,WHOLE,HALF,WHOLE,WHOLE,HALF]
MIXOLYDIAN = [WHOLE,WHOLE,HALF,WHOLE,WHOLE,HALF,WHOLE]
AEOLIAN = [WHOLE,HALF,WHOLE,WHOLE,HALF,WHOLE,WHOLE]
LOCRIAN = [HALF,WHOLE,WHOLE,HALF,WHOLE,WHOLE,WHOLE]

# INTERVALS
MIN2ND = 1
MAJ2ND = 2
MIN3RD = 3
MAJ3RD = 4
P4 = 5
TRI = 6
P5 = 7
MIN6TH = 8
MAJ6TH = 9
MIN7TH = 10
MAJ7TH = 11
OCT = 12

# RHYTHMIC DESCRIPTORS
EIGHTH = 0.5
QUARTER = 1
HALF = 2

# DIRECTIONAL DESCRIPTORS
ASCENDING = "ASCENDING"
DESCENDING = "DESCENDING"
BOTH = "BOTH"
CONSTANT = "CONSTANT"

# TEMPO - Measured in BPM.
SLOW = 150
MODERATE = 200
FAST = 300

# NOTES
NOTES = (("B#","C"),("C#","Db"),"D",("D#","Eb"),
         ("E","Fb"),("E#","F"),("F#","Gb"),"G",
         ("G#","Ab"),"A",("A#","Bb"),("B","Cb"))

# OCTAVE - Range encompasses all MIDI notes
OCTAVES = (-1,9)

# DEFAULTS
DEFAULT_CENTER = "C4"
DEFAULT_RANGE = 7
DEFAULT_MODE = IONIAN
DEFAULT_CONTOUR = BOTH
DEFAULT_TEMPO = MODERATE
DEFAULT_RHYTHM = [EIGHTH, EIGHTH, HALF]
DEFAULT_LENGTH = 3
DEFAULT_KEY = "C"
DEFAULT_INTERVAL = P5
